# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CCE' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CCE
  pod 'IQKeyboardManagerSwift'
  pod 'Firebase/Core'
  pod 'FBSDKLoginKit'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FacebookShare'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'lottie-ios'
  
end
